select * from customer limit(20)

--Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    "Gender",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Gender";



--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT
    "Customer ID",
    "Purchase Amount (USD)",
    "Discount Applied"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
        SELECT AVG("Purchase Amount (USD)")
        FROM customer
      );




--Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    "Item Purchased",
    AVG("Review Rating") AS avg_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;




--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
GROUP BY "Shipping Type";



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between ubscribers and non-subscribers.
SELECT 
    "Subscription Status",
    AVG("Purchase Amount (USD)") AS avg_spend,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    "Item Purchased",
    COUNT(*) FILTER (WHERE "Discount Applied" = 'Yes')::decimal / COUNT(*) * 100 AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    CASE 
        WHEN "Previous Purchases" = 0 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS segment_count
FROM customer
GROUP BY customer_segment;






--Q8. What are the top 3 most purchased products within each category?

SELECT 
    "Category",
    "Item Purchased",
    COUNT(*) AS purchase_count
FROM customer
GROUP BY "Category", "Item Purchased"
ORDER BY "Category", purchase_count DESC
LIMIT 3;





--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


SELECT 
    "Subscription Status",
    COUNT(*) AS customer_count
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";





-- Q10. What is the revenue contribution of each age group?

SELECT 
    CASE 
        WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
        WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
        WHEN "Age" BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END AS age_group,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY age_group;

